#!/usr/bin/env bash
# Generates the exact workflowScript for the next wave of a mission (D33).
# The lead passes the output verbatim to the pi-subagents `subagent` tool:
#   subagent({ workflowScript: <output>, context: "fresh", async: false })
# All data (who runs, with which brief) comes from the mission's files, so
# the lead relays orchestration instead of improvising it.
#
# Usage:
#   scripts/factory/workflow.sh contract    <feature>
#   scripts/factory/workflow.sh build-wave  <feature>
#   scripts/factory/workflow.sh review-wave <feature>
#   scripts/factory/workflow.sh validate    <feature>
#   scripts/factory/workflow.sh light       <slug> <base-ref>
set -euo pipefail
here="$(cd "$(dirname "$0")" && pwd)"
# shellcheck source=lib.sh
. "$here/lib.sh"

mode="${1:?usage: workflow.sh <contract|build-wave|review-wave|validate|light> <feature> ...}"
feature="${2:?usage: workflow.sh <mode> <feature> ...}"

tmp="$(mktemp -d)"; trap 'rm -rf "$tmp"' EXIT
items="$tmp/items.tsv"; : > "$items"

add() {                     # <key> <agent> <worktree:true|false> <brief args...>
  local key="$1" agent="$2" wt="$3"; shift 3
  bash "$here/brief.sh" "$@" > "$tmp/$key.brief"
  printf '%s\t%s\t%s\t%s\n' "$key" "$agent" "$wt" "$tmp/$key.brief" >> "$items"
}

json_args() {               # items.tsv → JSON array (node, else python3)
  if command -v node >/dev/null; then
    node -e '
      const fs = require("fs");
      const rows = fs.readFileSync(process.argv[1], "utf8").split("\n").filter(Boolean);
      const out = rows.map(r => { const [key, agent, wt, f] = r.split("\t");
        return { key, agent, worktree: wt === "true", task: fs.readFileSync(f, "utf8") }; });
      process.stdout.write(JSON.stringify(out, null, 2));' "$items"
  else
    python3 -c '
import json, sys
out = []
for r in open(sys.argv[1]).read().splitlines():
    if not r: continue
    key, agent, wt, f = r.split("\t")
    out.append({"key": key, "agent": agent, "worktree": wt == "true", "task": open(f).read()})
print(json.dumps(out, indent=2), end="")' "$items"
  fi
}

case "$mode" in
  contract)
    add contract-author factory-contract-author false contract-author "$feature"
    add contract-critic factory-contract-critic false contract-critic "$feature"
    body='const out = [];
for (const it of ITEMS) {            // sequential: the critic reads the author'"'"'s result
  const r = await runs.run(it.key, { agent: it.agent, task: it.task });
  out.push({ key: it.key, output: r.output });
}
return out;'
    ;;

  build-wave)
    if [ -n "$(git status --porcelain -- "$(mission_dir "$feature")")" ]; then
      die "uncommitted mission state: run scripts/factory/checkpoint.sh $feature first (worktrees branch from HEAD)"
    fi
    compute_ticket_state "$feature"
    [ ${#T_BUILD[@]} -gt 0 ] || die "nothing to build for $feature (run next.sh)"
    n=0
    for name in "${T_BUILD[@]}"; do
      [ "$n" -ge "$FACTORY_MAX_PARALLEL" ] && break
      agent=factory-worker
      [ "${T_ROUND[$name]:-0}" -ge 2 ] && agent=factory-worker-heavy      # D24 escalation
      add "$name" "$agent" true worker "$feature" "$name"
      n=$((n + 1))
    done
    body='const results = await runs.all(ITEMS.map(it => ({
  key: it.key, agent: it.agent, task: it.task, worktree: true,
})));
return results.map((r, i) => ({ ticket: ITEMS[i].key, output: r.output, artifactPaths: r.artifactPaths }));'
    ;;

  review-wave)
    compute_ticket_state "$feature"
    [ ${#T_REVIEW[@]} -gt 0 ] || die "nothing to review for $feature (run next.sh)"
    for name in "${T_REVIEW[@]}"; do
      add "$name" factory-reviewer false reviewer "$feature" "$name" "$(ticket_marker "$feature" "$name")"
    done
    body='const results = await runs.all(ITEMS.map(it => ({
  key: it.key, agent: it.agent, task: it.task,
})));
return results.map((r, i) => ({ ticket: ITEMS[i].key, output: r.output }));'
    ;;

  validate)
    add behavior factory-validator false validator "$feature" - "$(git rev-parse HEAD)"
    body='const it = ITEMS[0];
const r = await runs.run(it.key, { agent: it.agent, task: it.task });
return { output: r.output };'
    ;;

  light)
    base="${3:?usage: workflow.sh light <slug> <base-ref>}"
    add light factory-reviewer false light-reviewer "$feature" - "$(git rev-parse HEAD)" "$(git rev-parse "$base")"
    body='const it = ITEMS[0];
const r = await runs.run(it.key, { agent: it.agent, task: it.task });
return { output: r.output };'
    ;;

  *) die "unknown mode: $mode" ;;
esac

printf '// Generated by scripts/factory/workflow.sh %s %s. Pass verbatim; do not edit.\n' "$mode" "$feature"
printf 'const ITEMS = %s;\n' "$(json_args)"
printf '%s\n' "$body"
