// semantic-release configuration.
// develop → prereleases (x.y.z-rc.N), main → releases.
// Commit trailers (Co-Authored-By, Claude-Session, Signed-off-by) follow the
// BREAKING CHANGE footer in a commit body, so the parser folds them into the
// breaking-change note. finalizeContext strips them from every note, which
// cleans both CHANGELOG.md and the GitHub release.
const TRAILER = /^(Co-Authored-By|Claude-Session|Signed-off-by):/i;

const clean = (text = "") =>
  text.split("\n").filter((line) => !TRAILER.test(line.trim())).join("\n").trim();

module.exports = {
  branches: ["main", { name: "develop", prerelease: "rc" }],
  tagFormat: "v${version}",
  plugins: [
    ["@semantic-release/commit-analyzer", { preset: "conventionalcommits" }],
    ["@semantic-release/release-notes-generator", {
      preset: "conventionalcommits",
      writerOpts: {
        finalizeContext: (context) => {
          for (const group of context.noteGroups || []) {
            for (const note of group.notes || []) note.text = clean(note.text);
          }
          return context;
        },
      },
    }],
    ["@semantic-release/changelog", {
      changelogFile: "CHANGELOG.md",
      changelogTitle: "# Changelog\n\nGenerated by semantic-release from Conventional Commits. Curated notes per release, explaining each issue and its fix: [docs/releases/](docs/releases/).",
    }],
    ["@semantic-release/exec", { prepareCmd: "printf '%s\\n' '${nextRelease.version}' > .factory/VERSION" }],
    ["@semantic-release/git", {
      assets: ["CHANGELOG.md", ".factory/VERSION"],
      message: "chore(release): ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}",
    }],
    "@semantic-release/github",
  ],
};
